### ISSUE TITLE
Constant lengths as pointers?

### ISSUE THREAD

**Issue by jedisct1** [deislabs/wasi-experimental-http#33]
Hi,

In the `req()` function, constant lengths (`url`, `method`, `body`, `headers`) are passed as pointers.

Is there a reason not to pass them as `usize` directly and avoid indirections?

**Comment by radu-matei** [comment]
Not really - it was just a way to have consistency between the lengths send by the client and those written by the runtime, but you are right, directly passing the lengths makes sense.

Would you be interested in contributing this change?
(I'm happy to if you don't have the time.)

**Comment by jedisct1** [comment]
Done :)
