### ISSUE TITLE
Limit number of concurrent requests a module can send

### ISSUE THREAD

**Issue by radu-matei** [deislabs/wasi-experimental-http#46]
There should be a way that the number of concurrent requests can be set when configuring the HTTP library, similar to how the list of allowed hosts is configured.

What should be default if no such limit is set?

**Comment by jedisct1** [comment]
Indeed. This is more of an implementation detail than something in the specification, though.

The limit should probably be a parameter of `Http::new()`.

As for the default, I have no opinion. Maybe 8 to mimic what web browsers do?
