### ISSUE TITLE
WITX definition for the request API

### ISSUE THREAD

**Issue by radu-matei** [deislabs/wasi-experimental-http#5]
Currently there is no WITX support in this repository - the API is defined and implemented directly for Wasmtime, but if we wanted to support multiple runtimes (and even to keep the two crates in sync), it would be very helpful to have WITX definitions.

**Comment by jedisct1** [comment]
Don't rush too much on that one, as WITX is still a moving target, and changes completely break code generators.

**Comment by radu-matei** [comment]
This was implemented in #52, thanks a lot, @jedisct1!
